# Generated by Django 5.2.5 on 2025-08-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_announcement'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='class_assigned',
            field=models.ForeignKey(blank=True, help_text='The specific class section the student is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='faculty.class'),
        ),
    ]
