# Generated by Django 5.2.5 on 2025-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SCST', 'SC/ST'), ('TFWS', 'TFWS'), ('OBC', 'OBC'), ('EWS', 'EWS'), ('MINORITY', 'Minority'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
    ]
