# Generated by Django 5.2.5 on 2025-08-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_fee_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fee_category',
        ),
    ]
