# Generated by Django 5.2.5 on 2025-08-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(to='faculty.department'),
        ),
    ]
