# Generated by Django 5.2.4 on 2025-08-19 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_teacher_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_class', models.ForeignKey(blank=True, help_text='Optional: Post to a specific class.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.class')),
                ('teacher', models.ForeignKey(help_text='The teacher posting the announcement.', on_delete=django.db.models.deletion.CASCADE, to='faculty.teacher')),
            ],
        ),
    ]
