# Generated by Django 5.2.5 on 2025-08-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
