# Generated by Django 5.2.5 on 2025-08-21 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GENERAL', 'General'), ('SCST', 'SC/ST'), ('TFWS', 'TFWS'), ('OBC', 'OBC'), ('EWS', 'EWS'), ('MINORITY', 'Minority'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the reminder was/will be sent')),
                ('subject', models.CharField(help_text='Subject of the reminder email', max_length=200)),
                ('message', models.TextField(help_text='Reminder message content')),
                ('sent', models.BooleanField(default=False, help_text='Whether the reminder has been sent')),
                ('sent_date', models.DateTimeField(blank=True, help_text='When the reminder was actually sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this reminder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who will receive the reminder', on_delete=django.db.models.deletion.CASCADE, related_name='fee_reminders', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Reminder',
                'verbose_name_plural': 'Fee Reminders',
                'ordering': ['-reminder_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(help_text='Type of fee (Tuition, Library, Hostel, etc.)', max_length=100)),
                ('academic_year', models.CharField(help_text='Format: YYYY-YYYY', max_length=9)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Default fee amount', max_digits=10)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fee structure is currently active')),
                ('category', models.ForeignKey(help_text='Student category (General, SC/ST, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='fees.feecategory')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being paid in this transaction', max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('other', 'Other')], help_text='Method used for payment', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction/Receipt number for reference', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
                ('fee_structure', models.ForeignKey(help_text='Fee structure this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategoryAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SCST', 'SC/ST'), ('TFWS', 'TFWS'), ('OBC', 'OBC'), ('EWS', 'EWS'), ('MINORITY', 'Minority'), ('OTHER', 'Other')], help_text='Student category this fee applies to', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount for this category', max_digits=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_amounts', to='fees.feestructure')),
            ],
            options={
                'verbose_name_plural': 'Fee category amounts',
                'unique_together': {('fee_structure', 'category')},
            },
        ),
    ]
