# Generated by Django 5.2.5 on 2025-08-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='course',
            field=models.ForeignKey(default=1, help_text='Course this fee structure applies to', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='faculty.course'),
            preserve_default=False,
        ),
    ]
