# Generated by Django 5.2.5 on 2025-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='semester',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base fee amount', max_digits=10),
        ),
    ]
