# Generated by Django 5.2.5 on 2025-08-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_feestructure_category_and_more'),
        ('students', '0003_remove_student_fee_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeStatus',
            fields=[
            ],
            options={
                'verbose_name': 'Student Fee Status',
                'verbose_name_plural': 'Student Fee Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
    ]
