# Generated by Django 5.2.5 on 2025-08-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_add_fee_reminder_fields'),
        ('fees', '0004_studentfeestatus'),
    ]

    operations = [
    ]
