# Generated by Django 5.2.5 on 2025-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_merge_20250821_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereminder',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, help_text='Amount due for payment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feereminder',
            name='due_date',
            field=models.DateField(help_text='Due date for the payment'),
        ),
    ]
