# Generated by Django 5.2.5 on 2025-08-19 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_notification_user_notification_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_all_students',
            field=models.BooleanField(default=False, help_text='Check this box to send the notification to ALL students.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
