# Generated by Django 5.2.5 on 2025-08-11 17:03

from django.db import migrations, models
import django.db.models.deletion


def create_default_department(apps, schema_editor):
    Department = apps.get_model('faculty', 'Department')
    if not Department.objects.exists():
        Department.objects.create(name='Default Department')


def create_default_course(apps, schema_editor):
    Department = apps.get_model('faculty', 'Department')
    Course = apps.get_model('faculty', 'Course')
    if not Course.objects.exists():
        default_dept = Department.objects.first()
        if default_dept:
            Course.objects.create(name='Default Course', department=default_dept)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('faculty', '0002_auto_20250811_2233'),
    ]

    operations = [
        migrations.RunPython(create_default_department),
        migrations.RunPython(create_default_course),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.teacher'),
        ),
    ]
