# Generated by Django 5.2.5 on 2025-08-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_subject_and_more'),
        ('exams', '0002_auto_20250811_2233'),
        ('faculty', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
