# Generated by Django 5.2.5 on 2025-08-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationstatus',
            options={'verbose_name_plural': 'User notification statuses'},
        ),
    ]
