# Generated by Django 5.2.5 on 2025-08-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_recipients_notificationsender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSender',
        ),
    ]
