# Generated by Django 5.2.5 on 2025-08-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('faculty', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
    ]
