# Generated by Django 5.2.5 on 2025-08-17 12:43

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
    ]
