# Generated by Django 5.2.5 on 2025-08-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancereport_subject'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='classes_attended',
            field=models.PositiveIntegerField(default=1, help_text='Number of classes the student attended on this date.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classes_held',
            field=models.PositiveIntegerField(default=1, help_text='Total number of classes held on this date.'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject'),
        ),
    ]
